//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Reflection.AssemblyVersionAttribute("0.0.0.0")]
[assembly: global::Microsoft.Dss.Core.Attributes.ServiceDeclarationAttribute(global::Microsoft.Dss.Core.Attributes.DssServiceDeclaration.Proxy, SourceAssemblyKey="User.NxtCommon.Y2007.M07, Version=0.0.0.0, Culture=neutral, PublicKeyToken=aeea0a" +
    "482f1d42d7")]
[assembly: global::System.Security.SecurityTransparentAttribute()]
[assembly: global::System.Security.SecurityRulesAttribute(global::System.Security.SecurityRuleSet.Level1)]
[assembly: global::Microsoft.Dss.Core.Attributes.ServiceTypeRegistrationRequiredAttribute()]

namespace Microsoft.Robotics.Services.Sample.Lego.Nxt.Common.Proxy {
    
    
    [global::System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
    public class Contract {
        
        public const string Identifier = "http://schemas.microsoft.com/robotics/2007/07/lego/nxt/common.user.html";
    }
}
namespace Microsoft.Robotics.Services.Sample.Lego.Nxt.Commands.Proxy {
    
    
    [global::System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
    public class Contract {
        
        public const string Identifier = "http://schemas.microsoft.com/robotics/2007/07/lego/nxt/commands.user.html";
    }
}
