//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Reflection.AssemblyVersionAttribute("0.0.0.0")]
[assembly: global::Microsoft.Dss.Core.Attributes.ServiceDeclarationAttribute(global::Microsoft.Dss.Core.Attributes.DssServiceDeclaration.Transform, SourceAssemblyKey="User.HiTechnic.Y2007.M07, Version=0.0.0.0, Culture=neutral, PublicKeyToken=772187" +
    "607e5e5359")]
[assembly: global::System.Security.SecurityTransparentAttribute()]
[assembly: global::System.Security.SecurityRulesAttribute(global::System.Security.SecurityRuleSet.Level1)]

namespace Dss.Transforms.TransformUser {
    
    
    public class Transforms : global::Microsoft.Dss.Core.Transforms.TransformBase {
        
        static Transforms() {
            Register();
        }
        
        public static void Register() {
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::Microsoft.Robotics.Services.Sample.HiTechnic.PrototypeBoard.Proxy.PrototypeBoardState), new global::Microsoft.Dss.Core.Attributes.Transform(Microsoft_Robotics_Services_Sample_HiTechnic_PrototypeBoard_Proxy_PrototypeBoardState_TO_Microsoft_Robotics_Services_Sample_HiTechnic_PrototypeBoard_PrototypeBoardState));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::Microsoft.Robotics.Services.Sample.HiTechnic.PrototypeBoard.PrototypeBoardState), new global::Microsoft.Dss.Core.Attributes.Transform(Microsoft_Robotics_Services_Sample_HiTechnic_PrototypeBoard_PrototypeBoardState_TO_Microsoft_Robotics_Services_Sample_HiTechnic_PrototypeBoard_Proxy_PrototypeBoardState));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::Microsoft.Robotics.Services.Sample.HiTechnic.PrototypeBoard.Proxy.PrototypeBoardConfig), new global::Microsoft.Dss.Core.Attributes.Transform(Microsoft_Robotics_Services_Sample_HiTechnic_PrototypeBoard_Proxy_PrototypeBoardConfig_TO_Microsoft_Robotics_Services_Sample_HiTechnic_PrototypeBoard_PrototypeBoardConfig));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::Microsoft.Robotics.Services.Sample.HiTechnic.PrototypeBoard.PrototypeBoardConfig), new global::Microsoft.Dss.Core.Attributes.Transform(Microsoft_Robotics_Services_Sample_HiTechnic_PrototypeBoard_PrototypeBoardConfig_TO_Microsoft_Robotics_Services_Sample_HiTechnic_PrototypeBoard_Proxy_PrototypeBoardConfig));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::Microsoft.Robotics.Services.Sample.HiTechnic.PrototypeBoard.Proxy.LedConfig), new global::Microsoft.Dss.Core.Attributes.Transform(Microsoft_Robotics_Services_Sample_HiTechnic_PrototypeBoard_Proxy_LedConfig_TO_Microsoft_Robotics_Services_Sample_HiTechnic_PrototypeBoard_LedConfig));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::Microsoft.Robotics.Services.Sample.HiTechnic.PrototypeBoard.LedConfig), new global::Microsoft.Dss.Core.Attributes.Transform(Microsoft_Robotics_Services_Sample_HiTechnic_PrototypeBoard_LedConfig_TO_Microsoft_Robotics_Services_Sample_HiTechnic_PrototypeBoard_Proxy_LedConfig));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::Microsoft.Robotics.Services.Sample.HiTechnic.PrototypeBoard.Proxy.I2CReadHiTechnicPrototypeBoard), new global::Microsoft.Dss.Core.Attributes.Transform(Microsoft_Robotics_Services_Sample_HiTechnic_PrototypeBoard_Proxy_I2CReadHiTechnicPrototypeBoard_TO_Microsoft_Robotics_Services_Sample_HiTechnic_PrototypeBoard_I2CReadHiTechnicPrototypeBoard));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::Microsoft.Robotics.Services.Sample.HiTechnic.PrototypeBoard.I2CReadHiTechnicPrototypeBoard), new global::Microsoft.Dss.Core.Attributes.Transform(Microsoft_Robotics_Services_Sample_HiTechnic_PrototypeBoard_I2CReadHiTechnicPrototypeBoard_TO_Microsoft_Robotics_Services_Sample_HiTechnic_PrototypeBoard_Proxy_I2CReadHiTechnicPrototypeBoard));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::Microsoft.Robotics.Services.Sample.HiTechnic.PrototypeBoard.Proxy.I2CResponseHiTechnicPrototypeBoard), new global::Microsoft.Dss.Core.Attributes.Transform(Microsoft_Robotics_Services_Sample_HiTechnic_PrototypeBoard_Proxy_I2CResponseHiTechnicPrototypeBoard_TO_Microsoft_Robotics_Services_Sample_HiTechnic_PrototypeBoard_I2CResponseHiTechnicPrototypeBoard));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::Microsoft.Robotics.Services.Sample.HiTechnic.PrototypeBoard.I2CResponseHiTechnicPrototypeBoard), new global::Microsoft.Dss.Core.Attributes.Transform(Microsoft_Robotics_Services_Sample_HiTechnic_PrototypeBoard_I2CResponseHiTechnicPrototypeBoard_TO_Microsoft_Robotics_Services_Sample_HiTechnic_PrototypeBoard_Proxy_I2CResponseHiTechnicPrototypeBoard));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::Microsoft.Robotics.Services.Sample.HiTechnic.Compass.Proxy.CompassConfig), new global::Microsoft.Dss.Core.Attributes.Transform(Microsoft_Robotics_Services_Sample_HiTechnic_Compass_Proxy_CompassConfig_TO_Microsoft_Robotics_Services_Sample_HiTechnic_Compass_CompassConfig));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::Microsoft.Robotics.Services.Sample.HiTechnic.Compass.CompassConfig), new global::Microsoft.Dss.Core.Attributes.Transform(Microsoft_Robotics_Services_Sample_HiTechnic_Compass_CompassConfig_TO_Microsoft_Robotics_Services_Sample_HiTechnic_Compass_Proxy_CompassConfig));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::Microsoft.Robotics.Services.Sample.HiTechnic.Compass.Proxy.CompassSensorState), new global::Microsoft.Dss.Core.Attributes.Transform(Microsoft_Robotics_Services_Sample_HiTechnic_Compass_Proxy_CompassSensorState_TO_Microsoft_Robotics_Services_Sample_HiTechnic_Compass_CompassSensorState));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::Microsoft.Robotics.Services.Sample.HiTechnic.Compass.CompassSensorState), new global::Microsoft.Dss.Core.Attributes.Transform(Microsoft_Robotics_Services_Sample_HiTechnic_Compass_CompassSensorState_TO_Microsoft_Robotics_Services_Sample_HiTechnic_Compass_Proxy_CompassSensorState));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::Microsoft.Robotics.Services.Sample.HiTechnic.Compass.Proxy.CompassReading), new global::Microsoft.Dss.Core.Attributes.Transform(Microsoft_Robotics_Services_Sample_HiTechnic_Compass_Proxy_CompassReading_TO_Microsoft_Robotics_Services_Sample_HiTechnic_Compass_CompassReading));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::Microsoft.Robotics.Services.Sample.HiTechnic.Compass.CompassReading), new global::Microsoft.Dss.Core.Attributes.Transform(Microsoft_Robotics_Services_Sample_HiTechnic_Compass_CompassReading_TO_Microsoft_Robotics_Services_Sample_HiTechnic_Compass_Proxy_CompassReading));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::Microsoft.Robotics.Services.Sample.HiTechnic.Compass.Proxy.I2CReadHiTechnicCompassSensor), new global::Microsoft.Dss.Core.Attributes.Transform(Microsoft_Robotics_Services_Sample_HiTechnic_Compass_Proxy_I2CReadHiTechnicCompassSensor_TO_Microsoft_Robotics_Services_Sample_HiTechnic_Compass_I2CReadHiTechnicCompassSensor));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::Microsoft.Robotics.Services.Sample.HiTechnic.Compass.I2CReadHiTechnicCompassSensor), new global::Microsoft.Dss.Core.Attributes.Transform(Microsoft_Robotics_Services_Sample_HiTechnic_Compass_I2CReadHiTechnicCompassSensor_TO_Microsoft_Robotics_Services_Sample_HiTechnic_Compass_Proxy_I2CReadHiTechnicCompassSensor));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::Microsoft.Robotics.Services.Sample.HiTechnic.Compass.Proxy.I2CResponseHiTechnicCompassSensor), new global::Microsoft.Dss.Core.Attributes.Transform(Microsoft_Robotics_Services_Sample_HiTechnic_Compass_Proxy_I2CResponseHiTechnicCompassSensor_TO_Microsoft_Robotics_Services_Sample_HiTechnic_Compass_I2CResponseHiTechnicCompassSensor));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::Microsoft.Robotics.Services.Sample.HiTechnic.Compass.I2CResponseHiTechnicCompassSensor), new global::Microsoft.Dss.Core.Attributes.Transform(Microsoft_Robotics_Services_Sample_HiTechnic_Compass_I2CResponseHiTechnicCompassSensor_TO_Microsoft_Robotics_Services_Sample_HiTechnic_Compass_Proxy_I2CResponseHiTechnicCompassSensor));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::Microsoft.Robotics.Services.Sample.HiTechnic.Accelerometer.Proxy.AccelerometerConfig), new global::Microsoft.Dss.Core.Attributes.Transform(Microsoft_Robotics_Services_Sample_HiTechnic_Accelerometer_Proxy_AccelerometerConfig_TO_Microsoft_Robotics_Services_Sample_HiTechnic_Accelerometer_AccelerometerConfig));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::Microsoft.Robotics.Services.Sample.HiTechnic.Accelerometer.AccelerometerConfig), new global::Microsoft.Dss.Core.Attributes.Transform(Microsoft_Robotics_Services_Sample_HiTechnic_Accelerometer_AccelerometerConfig_TO_Microsoft_Robotics_Services_Sample_HiTechnic_Accelerometer_Proxy_AccelerometerConfig));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::Microsoft.Robotics.Services.Sample.HiTechnic.Accelerometer.Proxy.AccelerometerState), new global::Microsoft.Dss.Core.Attributes.Transform(Microsoft_Robotics_Services_Sample_HiTechnic_Accelerometer_Proxy_AccelerometerState_TO_Microsoft_Robotics_Services_Sample_HiTechnic_Accelerometer_AccelerometerState));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::Microsoft.Robotics.Services.Sample.HiTechnic.Accelerometer.AccelerometerState), new global::Microsoft.Dss.Core.Attributes.Transform(Microsoft_Robotics_Services_Sample_HiTechnic_Accelerometer_AccelerometerState_TO_Microsoft_Robotics_Services_Sample_HiTechnic_Accelerometer_Proxy_AccelerometerState));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::Microsoft.Robotics.Services.Sample.HiTechnic.Accelerometer.Proxy.I2CReadHiTechnicAccelerationSensor), new global::Microsoft.Dss.Core.Attributes.Transform(Microsoft_Robotics_Services_Sample_HiTechnic_Accelerometer_Proxy_I2CReadHiTechnicAccelerationSensor_TO_Microsoft_Robotics_Services_Sample_HiTechnic_Accelerometer_I2CReadHiTechnicAccelerationSensor));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::Microsoft.Robotics.Services.Sample.HiTechnic.Accelerometer.I2CReadHiTechnicAccelerationSensor), new global::Microsoft.Dss.Core.Attributes.Transform(Microsoft_Robotics_Services_Sample_HiTechnic_Accelerometer_I2CReadHiTechnicAccelerationSensor_TO_Microsoft_Robotics_Services_Sample_HiTechnic_Accelerometer_Proxy_I2CReadHiTechnicAccelerationSensor));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::Microsoft.Robotics.Services.Sample.HiTechnic.Accelerometer.Proxy.I2CResponseHiTechnicAccelerationSensor), new global::Microsoft.Dss.Core.Attributes.Transform(Microsoft_Robotics_Services_Sample_HiTechnic_Accelerometer_Proxy_I2CResponseHiTechnicAccelerationSensor_TO_Microsoft_Robotics_Services_Sample_HiTechnic_Accelerometer_I2CResponseHiTechnicAccelerationSensor));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::Microsoft.Robotics.Services.Sample.HiTechnic.Accelerometer.I2CResponseHiTechnicAccelerationSensor), new global::Microsoft.Dss.Core.Attributes.Transform(Microsoft_Robotics_Services_Sample_HiTechnic_Accelerometer_I2CResponseHiTechnicAccelerationSensor_TO_Microsoft_Robotics_Services_Sample_HiTechnic_Accelerometer_Proxy_I2CResponseHiTechnicAccelerationSensor));
        }
        
        public static object Microsoft_Robotics_Services_Sample_HiTechnic_PrototypeBoard_Proxy_PrototypeBoardState_TO_Microsoft_Robotics_Services_Sample_HiTechnic_PrototypeBoard_PrototypeBoardState(object transformFrom) {
            global::Microsoft.Robotics.Services.Sample.HiTechnic.PrototypeBoard.PrototypeBoardState target = new global::Microsoft.Robotics.Services.Sample.HiTechnic.PrototypeBoard.PrototypeBoardState();
            global::Microsoft.Robotics.Services.Sample.HiTechnic.PrototypeBoard.Proxy.PrototypeBoardState from = ((global::Microsoft.Robotics.Services.Sample.HiTechnic.PrototypeBoard.Proxy.PrototypeBoardState)(transformFrom));
            target.Connected = from.Connected;
            target.Name = from.Name;
            target.ManufactureInfo = from.ManufactureInfo;
            target.SensorPort = from.SensorPort;
            target.PollingFrequencyMs = from.PollingFrequencyMs;
            return target;
        }
        
        public static object Microsoft_Robotics_Services_Sample_HiTechnic_PrototypeBoard_PrototypeBoardState_TO_Microsoft_Robotics_Services_Sample_HiTechnic_PrototypeBoard_Proxy_PrototypeBoardState(object transformFrom) {
            global::Microsoft.Robotics.Services.Sample.HiTechnic.PrototypeBoard.Proxy.PrototypeBoardState target = new global::Microsoft.Robotics.Services.Sample.HiTechnic.PrototypeBoard.Proxy.PrototypeBoardState();
            global::Microsoft.Robotics.Services.Sample.HiTechnic.PrototypeBoard.PrototypeBoardState from = ((global::Microsoft.Robotics.Services.Sample.HiTechnic.PrototypeBoard.PrototypeBoardState)(transformFrom));
            target.Connected = from.Connected;
            target.Name = from.Name;
            target.ManufactureInfo = from.ManufactureInfo;
            target.SensorPort = from.SensorPort;
            target.PollingFrequencyMs = from.PollingFrequencyMs;
            return target;
        }
        
        public static object Microsoft_Robotics_Services_Sample_HiTechnic_PrototypeBoard_Proxy_PrototypeBoardConfig_TO_Microsoft_Robotics_Services_Sample_HiTechnic_PrototypeBoard_PrototypeBoardConfig(object transformFrom) {
            global::Microsoft.Robotics.Services.Sample.HiTechnic.PrototypeBoard.PrototypeBoardConfig target = new global::Microsoft.Robotics.Services.Sample.HiTechnic.PrototypeBoard.PrototypeBoardConfig();
            global::Microsoft.Robotics.Services.Sample.HiTechnic.PrototypeBoard.Proxy.PrototypeBoardConfig from = ((global::Microsoft.Robotics.Services.Sample.HiTechnic.PrototypeBoard.Proxy.PrototypeBoardConfig)(transformFrom));
            target.Name = from.Name;
            target.SensorPort = from.SensorPort;
            target.PollingFrequencyMs = from.PollingFrequencyMs;
            return target;
        }
        
        public static object Microsoft_Robotics_Services_Sample_HiTechnic_PrototypeBoard_PrototypeBoardConfig_TO_Microsoft_Robotics_Services_Sample_HiTechnic_PrototypeBoard_Proxy_PrototypeBoardConfig(object transformFrom) {
            global::Microsoft.Robotics.Services.Sample.HiTechnic.PrototypeBoard.Proxy.PrototypeBoardConfig target = new global::Microsoft.Robotics.Services.Sample.HiTechnic.PrototypeBoard.Proxy.PrototypeBoardConfig();
            global::Microsoft.Robotics.Services.Sample.HiTechnic.PrototypeBoard.PrototypeBoardConfig from = ((global::Microsoft.Robotics.Services.Sample.HiTechnic.PrototypeBoard.PrototypeBoardConfig)(transformFrom));
            target.Name = from.Name;
            target.SensorPort = from.SensorPort;
            target.PollingFrequencyMs = from.PollingFrequencyMs;
            return target;
        }
        
        public static object Microsoft_Robotics_Services_Sample_HiTechnic_PrototypeBoard_Proxy_LedConfig_TO_Microsoft_Robotics_Services_Sample_HiTechnic_PrototypeBoard_LedConfig(object transformFrom) {
            global::Microsoft.Robotics.Services.Sample.HiTechnic.PrototypeBoard.LedConfig target = new global::Microsoft.Robotics.Services.Sample.HiTechnic.PrototypeBoard.LedConfig();
            global::Microsoft.Robotics.Services.Sample.HiTechnic.PrototypeBoard.Proxy.LedConfig from = ((global::Microsoft.Robotics.Services.Sample.HiTechnic.PrototypeBoard.Proxy.LedConfig)(transformFrom));
            target.Status = ((global::Microsoft.Robotics.Services.Sample.HiTechnic.PrototypeBoard.LedStatus)(((int)(from.Status))));
            return target;
        }
        
        public static object Microsoft_Robotics_Services_Sample_HiTechnic_PrototypeBoard_LedConfig_TO_Microsoft_Robotics_Services_Sample_HiTechnic_PrototypeBoard_Proxy_LedConfig(object transformFrom) {
            global::Microsoft.Robotics.Services.Sample.HiTechnic.PrototypeBoard.Proxy.LedConfig target = new global::Microsoft.Robotics.Services.Sample.HiTechnic.PrototypeBoard.Proxy.LedConfig();
            global::Microsoft.Robotics.Services.Sample.HiTechnic.PrototypeBoard.LedConfig from = ((global::Microsoft.Robotics.Services.Sample.HiTechnic.PrototypeBoard.LedConfig)(transformFrom));
            target.Status = ((global::Microsoft.Robotics.Services.Sample.HiTechnic.PrototypeBoard.Proxy.LedStatus)(((int)(from.Status))));
            return target;
        }
        
        private static global::Microsoft.Robotics.Services.Sample.HiTechnic.PrototypeBoard.Proxy.I2CReadHiTechnicPrototypeBoard _cachedInstance0 = new global::Microsoft.Robotics.Services.Sample.HiTechnic.PrototypeBoard.Proxy.I2CReadHiTechnicPrototypeBoard();
        
        private static global::Microsoft.Robotics.Services.Sample.HiTechnic.PrototypeBoard.I2CReadHiTechnicPrototypeBoard _cachedInstance = new global::Microsoft.Robotics.Services.Sample.HiTechnic.PrototypeBoard.I2CReadHiTechnicPrototypeBoard();
        
        public static object Microsoft_Robotics_Services_Sample_HiTechnic_PrototypeBoard_Proxy_I2CReadHiTechnicPrototypeBoard_TO_Microsoft_Robotics_Services_Sample_HiTechnic_PrototypeBoard_I2CReadHiTechnicPrototypeBoard(object transformFrom) {
            return _cachedInstance;
        }
        
        public static object Microsoft_Robotics_Services_Sample_HiTechnic_PrototypeBoard_I2CReadHiTechnicPrototypeBoard_TO_Microsoft_Robotics_Services_Sample_HiTechnic_PrototypeBoard_Proxy_I2CReadHiTechnicPrototypeBoard(object transformFrom) {
            return _cachedInstance0;
        }
        
        private static global::Microsoft.Robotics.Services.Sample.HiTechnic.PrototypeBoard.Proxy.I2CResponseHiTechnicPrototypeBoard _cachedInstance2 = new global::Microsoft.Robotics.Services.Sample.HiTechnic.PrototypeBoard.Proxy.I2CResponseHiTechnicPrototypeBoard();
        
        private static global::Microsoft.Robotics.Services.Sample.HiTechnic.PrototypeBoard.I2CResponseHiTechnicPrototypeBoard _cachedInstance1 = new global::Microsoft.Robotics.Services.Sample.HiTechnic.PrototypeBoard.I2CResponseHiTechnicPrototypeBoard();
        
        public static object Microsoft_Robotics_Services_Sample_HiTechnic_PrototypeBoard_Proxy_I2CResponseHiTechnicPrototypeBoard_TO_Microsoft_Robotics_Services_Sample_HiTechnic_PrototypeBoard_I2CResponseHiTechnicPrototypeBoard(object transformFrom) {
            return _cachedInstance1;
        }
        
        public static object Microsoft_Robotics_Services_Sample_HiTechnic_PrototypeBoard_I2CResponseHiTechnicPrototypeBoard_TO_Microsoft_Robotics_Services_Sample_HiTechnic_PrototypeBoard_Proxy_I2CResponseHiTechnicPrototypeBoard(object transformFrom) {
            return _cachedInstance2;
        }
        
        public static object Microsoft_Robotics_Services_Sample_HiTechnic_Compass_Proxy_CompassConfig_TO_Microsoft_Robotics_Services_Sample_HiTechnic_Compass_CompassConfig(object transformFrom) {
            global::Microsoft.Robotics.Services.Sample.HiTechnic.Compass.CompassConfig target = new global::Microsoft.Robotics.Services.Sample.HiTechnic.Compass.CompassConfig();
            global::Microsoft.Robotics.Services.Sample.HiTechnic.Compass.Proxy.CompassConfig from = ((global::Microsoft.Robotics.Services.Sample.HiTechnic.Compass.Proxy.CompassConfig)(transformFrom));
            target.Name = from.Name;
            target.SensorPort = from.SensorPort;
            target.PollingFrequencyMs = from.PollingFrequencyMs;
            return target;
        }
        
        public static object Microsoft_Robotics_Services_Sample_HiTechnic_Compass_CompassConfig_TO_Microsoft_Robotics_Services_Sample_HiTechnic_Compass_Proxy_CompassConfig(object transformFrom) {
            global::Microsoft.Robotics.Services.Sample.HiTechnic.Compass.Proxy.CompassConfig target = new global::Microsoft.Robotics.Services.Sample.HiTechnic.Compass.Proxy.CompassConfig();
            global::Microsoft.Robotics.Services.Sample.HiTechnic.Compass.CompassConfig from = ((global::Microsoft.Robotics.Services.Sample.HiTechnic.Compass.CompassConfig)(transformFrom));
            target.Name = from.Name;
            target.SensorPort = from.SensorPort;
            target.PollingFrequencyMs = from.PollingFrequencyMs;
            return target;
        }
        
        public static object Microsoft_Robotics_Services_Sample_HiTechnic_Compass_Proxy_CompassSensorState_TO_Microsoft_Robotics_Services_Sample_HiTechnic_Compass_CompassSensorState(object transformFrom) {
            global::Microsoft.Robotics.Services.Sample.HiTechnic.Compass.CompassSensorState target = new global::Microsoft.Robotics.Services.Sample.HiTechnic.Compass.CompassSensorState();
            global::Microsoft.Robotics.Services.Sample.HiTechnic.Compass.Proxy.CompassSensorState from = ((global::Microsoft.Robotics.Services.Sample.HiTechnic.Compass.Proxy.CompassSensorState)(transformFrom));
            target.Connected = from.Connected;
            target.Name = from.Name;
            target.SensorPort = from.SensorPort;
            target.PollingFrequencyMs = from.PollingFrequencyMs;
            if ((from.Heading != null)) {
                target.Heading = ((global::Microsoft.Robotics.Services.Sample.HiTechnic.Compass.CompassReading)(Microsoft_Robotics_Services_Sample_HiTechnic_Compass_Proxy_CompassReading_TO_Microsoft_Robotics_Services_Sample_HiTechnic_Compass_CompassReading(from.Heading)));
            }
            else {
                target.Heading = null;
            }
            return target;
        }
        
        public static object Microsoft_Robotics_Services_Sample_HiTechnic_Compass_CompassSensorState_TO_Microsoft_Robotics_Services_Sample_HiTechnic_Compass_Proxy_CompassSensorState(object transformFrom) {
            global::Microsoft.Robotics.Services.Sample.HiTechnic.Compass.Proxy.CompassSensorState target = new global::Microsoft.Robotics.Services.Sample.HiTechnic.Compass.Proxy.CompassSensorState();
            global::Microsoft.Robotics.Services.Sample.HiTechnic.Compass.CompassSensorState from = ((global::Microsoft.Robotics.Services.Sample.HiTechnic.Compass.CompassSensorState)(transformFrom));
            target.Connected = from.Connected;
            target.Name = from.Name;
            target.SensorPort = from.SensorPort;
            target.PollingFrequencyMs = from.PollingFrequencyMs;
            global::Microsoft.Robotics.Services.Sample.HiTechnic.Compass.CompassReading tmp = from.Heading;
            if ((tmp != null)) {
                target.Heading = ((global::Microsoft.Robotics.Services.Sample.HiTechnic.Compass.Proxy.CompassReading)(Microsoft_Robotics_Services_Sample_HiTechnic_Compass_CompassReading_TO_Microsoft_Robotics_Services_Sample_HiTechnic_Compass_Proxy_CompassReading(tmp)));
            }
            return target;
        }
        
        public static object Microsoft_Robotics_Services_Sample_HiTechnic_Compass_Proxy_CompassReading_TO_Microsoft_Robotics_Services_Sample_HiTechnic_Compass_CompassReading(object transformFrom) {
            global::Microsoft.Robotics.Services.Sample.HiTechnic.Compass.CompassReading target = new global::Microsoft.Robotics.Services.Sample.HiTechnic.Compass.CompassReading();
            global::Microsoft.Robotics.Services.Sample.HiTechnic.Compass.Proxy.CompassReading from = ((global::Microsoft.Robotics.Services.Sample.HiTechnic.Compass.Proxy.CompassReading)(transformFrom));
            target.Degrees = from.Degrees;
            target.TimeStamp = from.TimeStamp;
            return target;
        }
        
        public static object Microsoft_Robotics_Services_Sample_HiTechnic_Compass_CompassReading_TO_Microsoft_Robotics_Services_Sample_HiTechnic_Compass_Proxy_CompassReading(object transformFrom) {
            global::Microsoft.Robotics.Services.Sample.HiTechnic.Compass.Proxy.CompassReading target = new global::Microsoft.Robotics.Services.Sample.HiTechnic.Compass.Proxy.CompassReading();
            global::Microsoft.Robotics.Services.Sample.HiTechnic.Compass.CompassReading from = ((global::Microsoft.Robotics.Services.Sample.HiTechnic.Compass.CompassReading)(transformFrom));
            target.Degrees = from.Degrees;
            target.TimeStamp = from.TimeStamp;
            return target;
        }
        
        private static global::Microsoft.Robotics.Services.Sample.HiTechnic.Compass.Proxy.I2CReadHiTechnicCompassSensor _cachedInstance4 = new global::Microsoft.Robotics.Services.Sample.HiTechnic.Compass.Proxy.I2CReadHiTechnicCompassSensor();
        
        private static global::Microsoft.Robotics.Services.Sample.HiTechnic.Compass.I2CReadHiTechnicCompassSensor _cachedInstance3 = new global::Microsoft.Robotics.Services.Sample.HiTechnic.Compass.I2CReadHiTechnicCompassSensor();
        
        public static object Microsoft_Robotics_Services_Sample_HiTechnic_Compass_Proxy_I2CReadHiTechnicCompassSensor_TO_Microsoft_Robotics_Services_Sample_HiTechnic_Compass_I2CReadHiTechnicCompassSensor(object transformFrom) {
            return _cachedInstance3;
        }
        
        public static object Microsoft_Robotics_Services_Sample_HiTechnic_Compass_I2CReadHiTechnicCompassSensor_TO_Microsoft_Robotics_Services_Sample_HiTechnic_Compass_Proxy_I2CReadHiTechnicCompassSensor(object transformFrom) {
            return _cachedInstance4;
        }
        
        public static object Microsoft_Robotics_Services_Sample_HiTechnic_Compass_Proxy_I2CResponseHiTechnicCompassSensor_TO_Microsoft_Robotics_Services_Sample_HiTechnic_Compass_I2CResponseHiTechnicCompassSensor(object transformFrom) {
            global::Microsoft.Robotics.Services.Sample.HiTechnic.Compass.I2CResponseHiTechnicCompassSensor target = new global::Microsoft.Robotics.Services.Sample.HiTechnic.Compass.I2CResponseHiTechnicCompassSensor();
            global::Microsoft.Robotics.Services.Sample.HiTechnic.Compass.Proxy.I2CResponseHiTechnicCompassSensor from = ((global::Microsoft.Robotics.Services.Sample.HiTechnic.Compass.Proxy.I2CResponseHiTechnicCompassSensor)(transformFrom));
            target.ModeControl = ((global::Microsoft.Robotics.Services.Sample.HiTechnic.Compass.CompassMode)(((int)(from.ModeControl))));
            target.Heading = from.Heading;
            return target;
        }
        
        public static object Microsoft_Robotics_Services_Sample_HiTechnic_Compass_I2CResponseHiTechnicCompassSensor_TO_Microsoft_Robotics_Services_Sample_HiTechnic_Compass_Proxy_I2CResponseHiTechnicCompassSensor(object transformFrom) {
            global::Microsoft.Robotics.Services.Sample.HiTechnic.Compass.Proxy.I2CResponseHiTechnicCompassSensor target = new global::Microsoft.Robotics.Services.Sample.HiTechnic.Compass.Proxy.I2CResponseHiTechnicCompassSensor();
            global::Microsoft.Robotics.Services.Sample.HiTechnic.Compass.I2CResponseHiTechnicCompassSensor from = ((global::Microsoft.Robotics.Services.Sample.HiTechnic.Compass.I2CResponseHiTechnicCompassSensor)(transformFrom));
            target.ModeControl = ((global::Microsoft.Robotics.Services.Sample.HiTechnic.Compass.Proxy.CompassMode)(((int)(from.ModeControl))));
            target.Heading = from.Heading;
            return target;
        }
        
        public static object Microsoft_Robotics_Services_Sample_HiTechnic_Accelerometer_Proxy_AccelerometerConfig_TO_Microsoft_Robotics_Services_Sample_HiTechnic_Accelerometer_AccelerometerConfig(object transformFrom) {
            global::Microsoft.Robotics.Services.Sample.HiTechnic.Accelerometer.AccelerometerConfig target = new global::Microsoft.Robotics.Services.Sample.HiTechnic.Accelerometer.AccelerometerConfig();
            global::Microsoft.Robotics.Services.Sample.HiTechnic.Accelerometer.Proxy.AccelerometerConfig from = ((global::Microsoft.Robotics.Services.Sample.HiTechnic.Accelerometer.Proxy.AccelerometerConfig)(transformFrom));
            target.Name = from.Name;
            target.SensorPort = from.SensorPort;
            target.PollingFrequencyMs = from.PollingFrequencyMs;
            return target;
        }
        
        public static object Microsoft_Robotics_Services_Sample_HiTechnic_Accelerometer_AccelerometerConfig_TO_Microsoft_Robotics_Services_Sample_HiTechnic_Accelerometer_Proxy_AccelerometerConfig(object transformFrom) {
            global::Microsoft.Robotics.Services.Sample.HiTechnic.Accelerometer.Proxy.AccelerometerConfig target = new global::Microsoft.Robotics.Services.Sample.HiTechnic.Accelerometer.Proxy.AccelerometerConfig();
            global::Microsoft.Robotics.Services.Sample.HiTechnic.Accelerometer.AccelerometerConfig from = ((global::Microsoft.Robotics.Services.Sample.HiTechnic.Accelerometer.AccelerometerConfig)(transformFrom));
            target.Name = from.Name;
            target.SensorPort = from.SensorPort;
            target.PollingFrequencyMs = from.PollingFrequencyMs;
            return target;
        }
        
        public static object Microsoft_Robotics_Services_Sample_HiTechnic_Accelerometer_Proxy_AccelerometerState_TO_Microsoft_Robotics_Services_Sample_HiTechnic_Accelerometer_AccelerometerState(object transformFrom) {
            global::Microsoft.Robotics.Services.Sample.HiTechnic.Accelerometer.AccelerometerState target = new global::Microsoft.Robotics.Services.Sample.HiTechnic.Accelerometer.AccelerometerState();
            global::Microsoft.Robotics.Services.Sample.HiTechnic.Accelerometer.Proxy.AccelerometerState from = ((global::Microsoft.Robotics.Services.Sample.HiTechnic.Accelerometer.Proxy.AccelerometerState)(transformFrom));
            target.Connected = from.Connected;
            target.Name = from.Name;
            target.SensorPort = from.SensorPort;
            target.PollingFrequencyMs = from.PollingFrequencyMs;
            if ((from.ZeroOffset != null)) {
                global::Microsoft.Robotics.Services.Sample.Lego.Nxt.Common.AccelerometerReading tmp = new global::Microsoft.Robotics.Services.Sample.Lego.Nxt.Common.AccelerometerReading();
                ((Microsoft.Dss.Core.IDssSerializable)(from.ZeroOffset)).CopyTo(((Microsoft.Dss.Core.IDssSerializable)(tmp)));
                target.ZeroOffset = tmp;
            }
            else {
                target.ZeroOffset = null;
            }
            if ((from.Tilt != null)) {
                global::Microsoft.Robotics.Services.Sample.Lego.Nxt.Common.AccelerometerReading tmp0 = new global::Microsoft.Robotics.Services.Sample.Lego.Nxt.Common.AccelerometerReading();
                ((Microsoft.Dss.Core.IDssSerializable)(from.Tilt)).CopyTo(((Microsoft.Dss.Core.IDssSerializable)(tmp0)));
                target.Tilt = tmp0;
            }
            else {
                target.Tilt = null;
            }
            return target;
        }
        
        public static object Microsoft_Robotics_Services_Sample_HiTechnic_Accelerometer_AccelerometerState_TO_Microsoft_Robotics_Services_Sample_HiTechnic_Accelerometer_Proxy_AccelerometerState(object transformFrom) {
            global::Microsoft.Robotics.Services.Sample.HiTechnic.Accelerometer.Proxy.AccelerometerState target = new global::Microsoft.Robotics.Services.Sample.HiTechnic.Accelerometer.Proxy.AccelerometerState();
            global::Microsoft.Robotics.Services.Sample.HiTechnic.Accelerometer.AccelerometerState from = ((global::Microsoft.Robotics.Services.Sample.HiTechnic.Accelerometer.AccelerometerState)(transformFrom));
            target.Connected = from.Connected;
            target.Name = from.Name;
            target.SensorPort = from.SensorPort;
            target.PollingFrequencyMs = from.PollingFrequencyMs;
            global::Microsoft.Robotics.Services.Sample.Lego.Nxt.Common.AccelerometerReading tmp = from.ZeroOffset;
            if ((tmp != null)) {
                global::Microsoft.Robotics.Services.Sample.Lego.Nxt.Common.AccelerometerReading tmp0 = new global::Microsoft.Robotics.Services.Sample.Lego.Nxt.Common.AccelerometerReading();
                ((Microsoft.Dss.Core.IDssSerializable)(tmp)).CopyTo(((Microsoft.Dss.Core.IDssSerializable)(tmp0)));
                target.ZeroOffset = tmp0;
            }
            global::Microsoft.Robotics.Services.Sample.Lego.Nxt.Common.AccelerometerReading tmp1 = from.Tilt;
            if ((tmp1 != null)) {
                global::Microsoft.Robotics.Services.Sample.Lego.Nxt.Common.AccelerometerReading tmp2 = new global::Microsoft.Robotics.Services.Sample.Lego.Nxt.Common.AccelerometerReading();
                ((Microsoft.Dss.Core.IDssSerializable)(tmp1)).CopyTo(((Microsoft.Dss.Core.IDssSerializable)(tmp2)));
                target.Tilt = tmp2;
            }
            return target;
        }
        
        private static global::Microsoft.Robotics.Services.Sample.HiTechnic.Accelerometer.Proxy.I2CReadHiTechnicAccelerationSensor _cachedInstance6 = new global::Microsoft.Robotics.Services.Sample.HiTechnic.Accelerometer.Proxy.I2CReadHiTechnicAccelerationSensor();
        
        private static global::Microsoft.Robotics.Services.Sample.HiTechnic.Accelerometer.I2CReadHiTechnicAccelerationSensor _cachedInstance5 = new global::Microsoft.Robotics.Services.Sample.HiTechnic.Accelerometer.I2CReadHiTechnicAccelerationSensor();
        
        public static object Microsoft_Robotics_Services_Sample_HiTechnic_Accelerometer_Proxy_I2CReadHiTechnicAccelerationSensor_TO_Microsoft_Robotics_Services_Sample_HiTechnic_Accelerometer_I2CReadHiTechnicAccelerationSensor(object transformFrom) {
            return _cachedInstance5;
        }
        
        public static object Microsoft_Robotics_Services_Sample_HiTechnic_Accelerometer_I2CReadHiTechnicAccelerationSensor_TO_Microsoft_Robotics_Services_Sample_HiTechnic_Accelerometer_Proxy_I2CReadHiTechnicAccelerationSensor(object transformFrom) {
            return _cachedInstance6;
        }
        
        public static object Microsoft_Robotics_Services_Sample_HiTechnic_Accelerometer_Proxy_I2CResponseHiTechnicAccelerationSensor_TO_Microsoft_Robotics_Services_Sample_HiTechnic_Accelerometer_I2CResponseHiTechnicAccelerationSensor(object transformFrom) {
            global::Microsoft.Robotics.Services.Sample.HiTechnic.Accelerometer.I2CResponseHiTechnicAccelerationSensor target = new global::Microsoft.Robotics.Services.Sample.HiTechnic.Accelerometer.I2CResponseHiTechnicAccelerationSensor();
            global::Microsoft.Robotics.Services.Sample.HiTechnic.Accelerometer.Proxy.I2CResponseHiTechnicAccelerationSensor from = ((global::Microsoft.Robotics.Services.Sample.HiTechnic.Accelerometer.Proxy.I2CResponseHiTechnicAccelerationSensor)(transformFrom));
            target.X = from.X;
            target.Y = from.Y;
            target.Z = from.Z;
            return target;
        }
        
        public static object Microsoft_Robotics_Services_Sample_HiTechnic_Accelerometer_I2CResponseHiTechnicAccelerationSensor_TO_Microsoft_Robotics_Services_Sample_HiTechnic_Accelerometer_Proxy_I2CResponseHiTechnicAccelerationSensor(object transformFrom) {
            global::Microsoft.Robotics.Services.Sample.HiTechnic.Accelerometer.Proxy.I2CResponseHiTechnicAccelerationSensor target = new global::Microsoft.Robotics.Services.Sample.HiTechnic.Accelerometer.Proxy.I2CResponseHiTechnicAccelerationSensor();
            global::Microsoft.Robotics.Services.Sample.HiTechnic.Accelerometer.I2CResponseHiTechnicAccelerationSensor from = ((global::Microsoft.Robotics.Services.Sample.HiTechnic.Accelerometer.I2CResponseHiTechnicAccelerationSensor)(transformFrom));
            target.X = from.X;
            target.Y = from.Y;
            target.Z = from.Z;
            return target;
        }
    }
}
